version: "3"
services:
  mysql:
    image: mysql:8.0.17
    ports:
      - 13306:3306
    volumes:
      - mysql-data:/var/lib/mysql
    environment:
      MYSQL_ROOT_PASSWORD: password

volumes:
  mysql-data:
